#include "nift/c_abi.h"
#include <fstream>
#include <iostream>
#include <string>
#include <chrono>
#include <malloc.h>
#include <sys/resource.h>
long rss(){std::ifstream f("/proc/self/status");std::string k;while(f>>k){if(k=="VmRSS:"){long n;f>>n;return n;}std::getline(f,k);}return 0;}
void run(nift_engine* e,const std::string& s){nift_script_result*r=nullptr;auto status=nift_engine_execute(e,s.data(),s.size(),nullptr,0,nullptr,nullptr,0,&r);if(status!=NIFT_OK||!r||!nift_script_result_ok(r)){nift_string err{};if(r)nift_script_result_error_message(r,&err);std::cerr<<std::string(err.data?err.data:"",err.length)<<"\n";exit(1);}nift_script_result_free(r);}
int main(int argc,char**argv){int n=std::stoi(argv[1]),size=std::stoi(argv[2]),repeat=argc>4?std::stoi(argv[4]):1;std::string mode=argv[3];std::string payload(size,'x');std::string body="b = ffi_buffer(p)";if(mode=="pointer")body="b = ffi_buffer(p); ffi_call(lib, \"identity\", \"ptr(buffer)\", b); ffi_call(lib, \"keep\", \"void(buffer)\", b); b = \"\"; raw = \"\"";if(mode=="callback")body="ffi_call(lib, \"callback\", \"i64(callback_i64,i64)\", cb, 1)";if(mode=="retain")body="a.push(ffi_buffer(p))";if(mode=="reuse")body="b = b";if(mode=="local")body="f()";if(mode=="subset")body="b = f(); if(i % 100 == 0) { a.push(b) }";if(mode=="alias")body="b = ffi_buffer(p); a = [b, deepcopy(b), {\"b\": b}]";std::string source="p := \""+payload+"\"\na := []\nb := ffi_buffer(p)\nfn(f()) { x := ffi_buffer(p); "+std::string(mode=="subset"?"return x":"return null")+" }\ni := 0\nwhile(i < "+std::to_string(n)+") { "+body+"; i += 1 }\nreturn null\n";if(mode=="pointer"||mode=="callback")source="lib := ffi_open(\".build/cp-e/fixture.so\")\nraw := \"\"\nfn(alloc(x)) { b := ffi_buffer(\""+payload+"\"); return 1 }\ncb := ffi_callback(alloc, \"i64(i64)\")\n"+source;if(argc>5){std::string kind=argv[5];auto pos=source.find("p := ");auto end=source.find("\n",pos);std::string init;if(kind=="bytes")init="p := bytes([";else init="p := [";for(int j=0;j<size;++j){if(j)init+=",";init+="120";}init+=kind=="bytes"?"])":"]";source.replace(pos,end-pos,init);}long before=rss();auto start=std::chrono::steady_clock::now();auto*e=nift_engine_new();for(int i=0;i<repeat;++i){if(mode=="fresh"&&i>0){nift_engine_free(e);e=nift_engine_new();}run(e,source);std::cout<<"phase="<<i<<" rss_kib="<<rss()<<"\n";}run(e,"return null");long scope=rss();nift_engine_free(e);long freed=rss();malloc_trim(0);struct rusage r{};getrusage(RUSAGE_SELF,&r);std::cout<<"count="<<n<<" payload="<<size<<" mode="<<mode<<" baseline="<<before<<" scope="<<scope<<" destroyed="<<freed<<" trimmed="<<rss()<<" peak="<<r.ru_maxrss<<" ms="<<std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count()<<"\n";}
