#!/usr/bin/env bash
# `nift init --handover` writes a project-root HANDOVER.md that is byte-for-byte
# identical to the canonical Nift handover (tests/fixtures/HANDOVER.md, which
# mirrors https://nift.dev/HANDOVER.md). Plain `nift init` must not create the
# file, and the handover must never land under the output directory.
set -u
NIFT_BIN="${NIFT_BIN:-$(pwd)/nift}"
FIXTURE="$(pwd)/tests/fixtures/HANDOVER.md"
CANONICAL_SHA="$(sha256sum "$FIXTURE" | cut -d' ' -f1)"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/nift-init-handover.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

fail() { echo "init-handover FAIL: $*" >&2; exit 1; }

check_no_handover() {
    local p="$1"
    [ ! -f "$p/HANDOVER.md" ] || fail "plain init unexpectedly created $p/HANDOVER.md"
    [ ! -f "$p/public/HANDOVER.md" ] || fail "handover leaked into $p/public/HANDOVER.md"
}

check_handover() {
    local p="$1"
    [ -f "$p/HANDOVER.md" ] || fail "expected $p/HANDOVER.md not created"
    [ -f "$p/public/HANDOVER.md" ] && fail "handover must not be written under public/"
    local got="$(sha256sum "$p/HANDOVER.md" | cut -d' ' -f1)"
    [ "$got" = "$CANONICAL_SHA" ] || fail "HANDOVER.md not byte-identical to canonical (got $got, want $CANONICAL_SHA)"
}

# Inverse: plain init must not create the handover.
P="$TMP/plain"; mkdir -p "$P"
(cd "$P" && "$NIFT_BIN" init >/dev/null 2>&1) || fail "plain init failed"
check_no_handover "$P"

# Primary: init --handover writes a byte-identical root HANDOVER.md.
P="$TMP/handover"; mkdir -p "$P"
(cd "$P" && "$NIFT_BIN" init --handover >/dev/null 2>&1) || fail "init --handover failed"
check_handover "$P"

# Combinations with existing init options/targets.
for combo in "--handover --target=vercel" "--handover --target=netlify" "--handover --ext=.php" "--handover --target=azure"; do
    P="$TMP/$(echo "$combo" | tr ' =.' '---')"; mkdir -p "$P"
    (cd "$P" && $NIFT_BIN init $combo >/dev/null 2>&1) || fail "init $combo failed"
    check_handover "$P"
done

echo "init-handover smoke test passed: HANDOVER.md generated byte-for-byte in project root; plain init untouched"
