import pathlib,json,subprocess,os,re
b=pathlib.Path('.build/cp410');rows=json.loads((b/'probes.json').read_text());names=['official-sort','captured-sort','sort-index','sort-identity','map-identity','sort-arithmetic','call-scalar','call-closure','call-callback','official-bfs','official-json-transform','frequency'];phase_binary=str((b/'phases/nift-phases').resolve());results=[]
for name in names:
 candidates=[r for r in rows if r['name']==name];r=next((x for x in candidates if x['n']==2000),candidates[0]);q=subprocess.run([phase_binary,r['path']],capture_output=True,text=True,check=True);assert q.stdout.strip()==r['expected'],(name,q.stdout);(b/'phases'/(name+'-counters.log')).write_text(q.stderr);phases={m[0]:dict(calls=int(m[1]),allocations=int(m[2]),bytes=int(m[3])) for m in re.findall(r'phase (\w+) calls=(\d+) allocations=(\d+) bytes=(\d+)',q.stderr)}
 if name in ['official-sort','captured-sort','sort-index','map-identity']:
  for phase in ['factory','instance','metadata','capture','registration','arguments','frame','body','key','decoration','sorting','result','cleanup','returned_key']:
   if not phases[phase]['calls']:continue
   out=b/'phases'/f'{name}-{phase}.callgrind';q=subprocess.run(['valgrind','--tool=callgrind','--collect-atstart=no','--callgrind-out-file='+str(out),phase_binary,r['path']],env={**os.environ,'CP51_PHASE':phase},capture_output=True,text=True,check=True,timeout=600);phases[phase]['instructions']=int(re.search(r'^summary: (\d+)',out.read_text(),re.M)[1])
 events=re.search(r'events instances=(\d+) capture_entries=(\d+) frame_capture_entries=(\d+) comparisons=(\d+)',q.stderr);item=dict(name=name,n=r['n'],phases=phases,events=dict(zip(['instances','capture_entries','frame_capture_entries','comparisons'],map(int,events.groups()))));results.append(item);(b/'phases/metrics.json').write_text(json.dumps(results,indent=2)+'\n');print('PHASES',name,item['events'],flush=True)
life=[];binary=str((b/'lifecycle/nift-counter').resolve())
for name in names:
 candidates=[r for r in rows if r['name']==name];r=next((x for x in candidates if x['n']==2000),candidates[0]);q=subprocess.run([binary,r['path']],capture_output=True,text=True,check=True);assert q.stdout.strip()==r['expected'];m=re.search(r'value-counts ctor=(\d+) copy_ctor=(\d+) move_ctor=(\d+) copy_assign=(\d+) move_assign=(\d+) dtor=(\d+)',q.stderr);assert m;qdata=dict(name=name,n=r['n'],counts=dict(zip(['constructors','copy_constructors','move_constructors','copy_assignments','move_assignments','destructors'],map(int,m.groups()))));life.append(qdata);(b/'lifecycle/counts.json').write_text(json.dumps(life,indent=2)+'\n');print('LIFECYCLE',name,qdata['counts'],flush=True)
