#include "ReStructuredText.h"
#include <markup/Markup.h>
#include <algorithm>
#include <cctype>
namespace markup::rst { namespace {
constexpr std::size_t max_input_bytes=64U*1024U*1024U;
std::string normalize(const std::string& input){std::string out;out.reserve(input.size());std::size_t column=0;for(std::size_t i=0;i<input.size();++i){unsigned char c=static_cast<unsigned char>(input[i]);if(!c){out+="\xef\xbf\xbd";column+=3;}else if(c=='\r'){out+='\n';column=0;if(i+1<input.size()&&input[i+1]=='\n')++i;}else if(c=='\n'){out+='\n';column=0;}else if(c=='\t'){std::size_t spaces=8-column%8;out.append(spaces,' ');column+=spaces;}else{out+=static_cast<char>(c);++column;}}return out;}
std::vector<std::string> lines_of(const std::string& input){std::vector<std::string> lines;std::size_t at=0;while(at<input.size()){auto end=input.find('\n',at);lines.push_back(input.substr(at,end==std::string::npos?std::string::npos:end-at));if(end==std::string::npos)break;at=end+1;}return lines;}
std::string escape(const std::string&s,bool attr=false){std::string o;for(char c:s)switch(c){case'&':o+="&amp;";break;case'<':o+="&lt;";break;case'>':o+="&gt;";break;case'"':o+=attr?"&quot;":"\"";break;default:o+=c;}return o;}
std::string slug(std::string s);
std::vector<Inline> parse_inlines(const std::string&text,Range source){std::vector<Inline>out;Inline plain;plain.source=source;auto flush=[&]{if(!plain.text.empty()){out.push_back(plain);plain.text.clear();}};for(std::size_t i=0;i<text.size();){if(text[i]=='\\'&&i+1<text.size()){plain.text+=text[i+1];i+=2;continue;}
 if(text[i]=='`'){auto close=text.find("`_",i+1);if(close!=std::string::npos){std::string inside=text.substr(i+1,close-i-1);auto angle=inside.rfind(" <");if(angle!=std::string::npos&&inside.back()=='>'){flush();Inline n;n.kind=InlineKind::Link;n.text=inside.substr(0,angle);n.target=inside.substr(angle+2,inside.size()-angle-3);n.source=source;n.children=parse_inlines(n.text,source);out.push_back(std::move(n));i=close+2;continue;}}}
 if(i+2<text.size()&&text[i]=='|' ){auto close=text.find('|',i+1);if(close!=std::string::npos){flush();Inline n;n.kind=InlineKind::Substitution;n.target=text.substr(i+1,close-i-1);n.source=source;out.push_back(std::move(n));i=close+1;continue;}}
 if(text[i]==':' ){auto colon=text.find(":`",i+1);if(colon!=std::string::npos){auto close=text.find('`',colon+2);if(close!=std::string::npos){flush();Inline n;n.kind=InlineKind::Role;n.role=text.substr(i+1,colon-i-1);n.text=text.substr(colon+2,close-colon-2);n.source=source;out.push_back(std::move(n));i=close+1;continue;}}}
 if(text[i]=='['){auto close=text.find("]_",i+1);if(close!=std::string::npos){flush();Inline n;n.kind=InlineKind::Footnote;n.target=n.text=text.substr(i+1,close-i-1);n.source=source;out.push_back(std::move(n));i=close+2;continue;}}
 if(text.compare(i,7,"http://")==0||text.compare(i,8,"https://")==0){std::size_t end=i;while(end<text.size()&&!std::isspace(static_cast<unsigned char>(text[end])))++end;flush();Inline n;n.kind=InlineKind::Link;n.target=n.text=text.substr(i,end-i);Inline label;label.text=n.text;label.source=source;n.children.push_back(std::move(label));n.source=source;out.push_back(std::move(n));i=end;continue;}
 struct D{const char*m;InlineKind k;};static const D ds[]={{"**",InlineKind::Strong},{"``",InlineKind::Literal},{"*",InlineKind::Emphasis}};bool found=false;for(auto d:ds){std::string m=d.m;if(text.compare(i,m.size(),m))continue;if(i&&std::isalnum(static_cast<unsigned char>(text[i-1])))continue;auto e=text.find(m,i+m.size());if(e==std::string::npos||e==i+m.size())continue;flush();Inline n;n.kind=d.k;n.text=text.substr(i+m.size(),e-i-m.size());n.source=source;if(d.k!=InlineKind::Literal)n.children=parse_inlines(n.text,source);out.push_back(std::move(n));i=e+m.size();found=true;break;}if(found)continue;
 if(std::isalnum(static_cast<unsigned char>(text[i]))){std::size_t end=i;while(end<text.size()&&(std::isalnum(static_cast<unsigned char>(text[end]))||text[end]=='-'))++end;if(end<text.size()&&text[end]=='_'){flush();Inline n;n.kind=InlineKind::Reference;n.text=text.substr(i,end-i);n.target=slug(n.text);n.source=source;out.push_back(std::move(n));i=end+1;continue;}}
 plain.text+=text[i++];}flush();return out;}
bool adornment(const std::string&s){if(s.size()<4)return false;char c=s[0];if(std::isalnum(static_cast<unsigned char>(c))||std::isspace(static_cast<unsigned char>(c)))return false;for(char x:s)if(x!=c)return false;return true;}
std::string slug(std::string s){std::string o;for(unsigned char c:s){if(std::isalnum(c))o+=static_cast<char>(std::tolower(c));else if((c==' '||c=='-'||c=='_')&&!o.empty()&&o.back()!='-')o+='-';}while(!o.empty()&&o.back()=='-')o.pop_back();return o;}
std::string trim(const std::string&s){auto a=s.find_first_not_of(' ');if(a==std::string::npos)return{};auto b=s.find_last_not_of(' ');return s.substr(a,b-a+1);}
std::vector<std::string> split_columns(const std::string&s){std::vector<std::string>v;std::size_t at=0;while(at<s.size()){while(at<s.size()&&s[at]==' ')++at;if(at==s.size())break;auto end=at;while(end<s.size()&&!(s[end]==' '&&end+1<s.size()&&s[end+1]==' '))++end;v.push_back(trim(s.substr(at,end-at)));at=end;}return v;}
bool simple_border(const std::string&s){auto cols=split_columns(s);if(cols.size()<2)return false;for(const auto&c:cols)for(char x:c)if(x!='=')return false;return true;}
bool grid_border(const std::string&s){return s.size()>4&&s.front()=='+'&&s.back()=='+'&&s.find('-')!=std::string::npos;}
Block table_row(const std::vector<std::string>&cells){Block row;for(const auto&value:cells){Block cell;cell.text=value;cell.inlines=parse_inlines(value,{});row.items.push_back(std::move(cell));}return row;}
bool expand_resources(const std::string&input,const Options&options,const std::string&identity,std::vector<std::string>&stack,std::string&output,std::string&error,unsigned depth=0){if(depth>32){error="reStructuredText include depth exceeds 32";return false;}if(input.size()>max_input_bytes||output.size()+input.size()>max_input_bytes){error="reStructuredText expanded input exceeds 64 MiB";return false;}auto lines=lines_of(normalize(input));for(std::size_t i=0;i<lines.size();++i){auto value=lines[i];if(value.rfind(".. include::",0)==0){auto target=trim(value.substr(12));if(!options.rst_resource_resolver){if(options.rst_diagnostic)options.rst_diagnostic("line "+std::to_string(i+1)+": include directive disabled: "+target);continue;}std::string content,canonical,reason;if(!options.rst_resource_resolver(identity,target,content,canonical,reason)){error=reason.empty()?"reStructuredText include could not be resolved: "+target:reason;return false;}if(std::find(stack.begin(),stack.end(),canonical)!=stack.end()){error="reStructuredText include cycle: "+canonical;return false;}if(options.rst_dependency)options.rst_dependency(canonical);stack.push_back(canonical);if(!expand_resources(content,options,canonical,stack,output,error,depth+1))return false;stack.pop_back();}else{output+=value;if(i+1<lines.size()||(!input.empty()&&input.back()=='\n'))output+='\n';}}return true;}
void parse_blocks(const std::vector<std::string>&lines,std::size_t&line,std::vector<Block>&blocks,std::map<char,unsigned>&levels,unsigned parent=0){while(line<lines.size()){while(line<lines.size()&&lines[line].empty())++line;if(line>=lines.size())break;
 if(line+1<lines.size()&&adornment(lines[line+1])&&lines[line+1].size()>=lines[line].size()){
  char mark=lines[line+1][0];if(!levels.count(mark))levels[mark]=static_cast<unsigned>(levels.size()+1);unsigned level=levels[mark];if(parent&&level<=parent)return;Block section;section.kind=BlockKind::Section;section.title=lines[line];section.name=slug(section.title);section.level=level;section.source.begin={line+1,1};line+=2;parse_blocks(lines,line,section.blocks,levels,level);section.source.end={line?line:1,1};blocks.push_back(std::move(section));continue;}
 if(adornment(lines[line])){Block b;b.kind=BlockKind::Transition;b.source.begin=b.source.end={line+1,1};++line;blocks.push_back(std::move(b));continue;}
 if(simple_border(lines[line])&&line+2<lines.size()){std::size_t first=line++;Block table;table.kind=BlockKind::Table;table.style="simple";while(line<lines.size()&&!simple_border(lines[line]))table.items.push_back(table_row(split_columns(lines[line++])));if(line<lines.size())++line;while(line<lines.size()&&!lines[line].empty()){table.items.push_back(table_row(split_columns(lines[line++])));if(line<lines.size()&&simple_border(lines[line])){++line;break;}}table.source.begin={first+1,1};table.source.end={line,1};blocks.push_back(std::move(table));continue;}
 if(grid_border(lines[line])&&line+2<lines.size()){std::size_t first=line++;Block table;table.kind=BlockKind::Table;table.style="grid";while(line<lines.size()){if(lines[line].size()>2&&lines[line].front()=='|'&&lines[line].back()=='|'){std::vector<std::string>cells;std::size_t at=1;while(at<lines[line].size()-1){auto end=lines[line].find('|',at);if(end==std::string::npos)break;cells.push_back(trim(lines[line].substr(at,end-at)));at=end+1;}table.items.push_back(table_row(cells));++line;}else if(grid_border(lines[line])){++line;if(line>=lines.size()||lines[line].empty())break;}else break;}table.source.begin={first+1,1};table.source.end={line,1};blocks.push_back(std::move(table));continue;}
 if(lines[line].rfind(".. ",0)==0){auto marker=lines[line].find("::",3);if(marker!=std::string::npos){std::size_t first=line;Block b;b.kind=BlockKind::Directive;b.name=trim(lines[line].substr(3,marker-3));b.argument=trim(lines[line].substr(marker+2));++line;while(line<lines.size()&&lines[line].empty())++line;while(line<lines.size()&&lines[line].rfind("   ",0)==0){if(!b.text.empty())b.text+='\n';b.text+=lines[line++].substr(3);}b.inlines=parse_inlines(b.text,{});b.source.begin={first+1,1};b.source.end={line,1};blocks.push_back(std::move(b));continue;}}
 if(lines[line].rfind(".. [",0)==0){auto close=lines[line].find(']');if(close!=std::string::npos){Block b;b.kind=std::isdigit(static_cast<unsigned char>(lines[line][4]))?BlockKind::Footnote:BlockKind::Citation;b.name=lines[line].substr(4,close-4);b.text=lines[line].substr(close+1);if(!b.text.empty()&&b.text[0]==' ')b.text.erase(0,1);b.inlines=parse_inlines(b.text,{});b.source.begin=b.source.end={line+1,1};++line;blocks.push_back(std::move(b));continue;}}
 if(lines[line].rfind(".. ",0)==0){Block b;b.kind=BlockKind::Comment;b.source.begin={line+1,1};++line;while(line<lines.size()&&lines[line].rfind("   ",0)==0)++line;blocks.push_back(std::move(b));continue;}
 auto bullet=[&](const std::string&s){return s.size()>2&&(s[0]=='*'||s[0]=='+'||s[0]=='-')&&s[1]==' ';};
 auto enumerated=[&](const std::string&s){std::size_t n=0;while(n<s.size()&&std::isdigit(static_cast<unsigned char>(s[n])))++n;return n&&n+1<s.size()&&s[n]=='.'&&s[n+1]==' ';};
 if(bullet(lines[line])||enumerated(lines[line])||lines[line].rfind("#. ",0)==0){bool ordered=!bullet(lines[line]);Block list;list.kind=ordered?BlockKind::EnumeratedList:BlockKind::BulletList;list.source.begin={line+1,1};while(line<lines.size()){
   bool match=ordered?(enumerated(lines[line])||lines[line].rfind("#. ",0)==0):bullet(lines[line]);if(!match)break;std::size_t cut=ordered?(lines[line].find(' ')+1):2;Block item;item.text=lines[line].substr(cut);item.source.begin=item.source.end={line+1,1};item.inlines=parse_inlines(item.text,item.source);list.items.push_back(std::move(item));++line;}
  list.source.end={line,1};blocks.push_back(std::move(list));continue;}
 if(lines[line].size()>3&&lines[line][0]==':'){auto end=lines[line].find(':',1);if(end!=std::string::npos){Block fields;fields.kind=BlockKind::FieldList;fields.source.begin={line+1,1};while(line<lines.size()&&lines[line].size()>3&&lines[line][0]==':'){auto stop=lines[line].find(':',1);if(stop==std::string::npos)break;Block item;item.title=lines[line].substr(1,stop-1);item.text=lines[line].substr(stop+1);if(!item.text.empty()&&item.text[0]==' ')item.text.erase(0,1);item.inlines=parse_inlines(item.text,{});fields.items.push_back(std::move(item));++line;}fields.source.end={line,1};blocks.push_back(std::move(fields));continue;}}
 if(line+1<lines.size()&&!lines[line].empty()&&!std::isspace(static_cast<unsigned char>(lines[line][0]))&&lines[line+1].rfind("  ",0)==0){Block list;list.kind=BlockKind::DefinitionList;list.source.begin={line+1,1};while(line+1<lines.size()&&!lines[line].empty()&&!std::isspace(static_cast<unsigned char>(lines[line][0]))&&lines[line+1].rfind("  ",0)==0){Block item;item.title=lines[line++];item.text=lines[line++].substr(2);item.inlines=parse_inlines(item.text,{});list.items.push_back(std::move(item));while(line<lines.size()&&lines[line].empty())++line;}list.source.end={line,1};blocks.push_back(std::move(list));continue;}
 if(lines[line].rfind("| ",0)==0){std::size_t first=line;Block b;b.kind=BlockKind::LineBlock;while(line<lines.size()&&lines[line].rfind("| ",0)==0){if(!b.text.empty())b.text+='\n';b.text+=lines[line++].substr(2);}b.source.begin={first+1,1};b.source.end={line,1};blocks.push_back(std::move(b));continue;}
 if(lines[line].rfind(">>> ",0)==0){std::size_t first=line;Block b;b.kind=BlockKind::Doctest;while(line<lines.size()&&!lines[line].empty()){if(!b.text.empty())b.text+='\n';b.text+=lines[line++];}b.source.begin={first+1,1};b.source.end={line,1};blocks.push_back(std::move(b));continue;}
 if(lines[line].size()>=2&&lines[line].substr(lines[line].size()-2)=="::"&&line+1<lines.size()){
  std::string lead=lines[line];lead.pop_back();Block p;p.text=lead;p.source.begin=p.source.end={line+1,1};p.inlines=parse_inlines(lead,p.source);blocks.push_back(std::move(p));++line;while(line<lines.size()&&lines[line].empty())++line;
  if(line<lines.size()&&lines[line].rfind("   ",0)==0){std::size_t first=line;Block b;b.kind=BlockKind::Literal;while(line<lines.size()&&(lines[line].empty()||lines[line].rfind("   ",0)==0)){if(!b.text.empty())b.text+='\n';b.text+=lines[line].empty()?"":lines[line].substr(3);++line;}b.source.begin={first+1,1};b.source.end={line,1};blocks.push_back(std::move(b));}continue;}
 if(lines[line].rfind("   ",0)==0){std::size_t first=line;std::string text;while(line<lines.size()&&(lines[line].empty()||lines[line].rfind("   ",0)==0)){if(!text.empty())text+='\n';text+=lines[line].empty()?"":lines[line].substr(3);++line;}Block b;b.kind=BlockKind::BlockQuote;b.text=text;b.source.begin={first+1,1};b.source.end={line,1};b.inlines=parse_inlines(text,b.source);blocks.push_back(std::move(b));continue;}
 std::size_t first=line;std::string text=lines[line++];while(line<lines.size()&&!lines[line].empty()){if(line+1<lines.size()&&adornment(lines[line+1]))break;text+='\n';text+=lines[line++];}Block b;b.source.begin={first+1,1};b.source.end={line,lines[line-1].size()};b.text=text;b.inlines=parse_inlines(text,b.source);blocks.push_back(std::move(b));}}
std::string render_inlines(const std::vector<Inline>&nodes){std::string o;for(auto&n:nodes)switch(n.kind){case InlineKind::Text:o+=escape(n.text);break;case InlineKind::Emphasis:o+="<em>"+render_inlines(n.children)+"</em>";break;case InlineKind::Strong:o+="<strong>"+render_inlines(n.children)+"</strong>";break;case InlineKind::Literal:o+="<code>"+escape(n.text)+"</code>";break;case InlineKind::Link:o+="<a href=\""+escape(n.target,true)+"\">"+render_inlines(n.children)+"</a>";break;case InlineKind::Reference:o+="<a href=\""+escape(n.target,true)+"\">"+escape(n.text)+"</a>";break;case InlineKind::Footnote:o+="<a class=\"footnote-reference\" href=\"#footnote-"+escape(n.target,true)+"\">["+escape(n.text)+"]</a>";break;case InlineKind::Substitution:o+="|"+escape(n.target)+"|";break;case InlineKind::Role:{auto r=n.role;if(r=="emphasis"||r=="em")o+="<em>"+escape(n.text)+"</em>";else if(r=="strong")o+="<strong>"+escape(n.text)+"</strong>";else if(r=="math")o+="<span class=\"math\">"+escape(n.text)+"</span>";else if(r=="subscript"||r=="sub")o+="<sub>"+escape(n.text)+"</sub>";else if(r=="superscript"||r=="sup")o+="<sup>"+escape(n.text)+"</sup>";else if(r=="title-reference"||r=="title")o+="<cite>"+escape(n.text)+"</cite>";else o+="<code class=\""+escape(r,true)+"\">"+escape(n.text)+"</code>";break;}default:o+=escape(n.text);}return o;}
std::string render_blocks(const std::vector<Block>&blocks){
 std::string o;
 for(const auto&b:blocks){
  if(b.kind==BlockKind::Paragraph)o+="<p>"+render_inlines(b.inlines)+"</p>\n";
  else if(b.kind==BlockKind::Section)o+="<section id=\""+escape(b.name,true)+"\">\n<h"+std::to_string(b.level)+">"+escape(b.title)+"</h"+std::to_string(b.level)+">\n"+render_blocks(b.blocks)+"</section>\n";
  else if(b.kind==BlockKind::Transition)o+="<hr>\n";
  else if(b.kind==BlockKind::BlockQuote)o+="<blockquote>\n<p>"+render_inlines(b.inlines)+"</p>\n</blockquote>\n";
  else if(b.kind==BlockKind::Literal)o+="<pre class=\"literal-block\">"+escape(b.text)+"</pre>\n";
  else if(b.kind==BlockKind::Doctest)o+="<pre class=\"doctest-block\">"+escape(b.text)+"</pre>\n";
  else if(b.kind==BlockKind::BulletList||b.kind==BlockKind::EnumeratedList){bool ordered=b.kind==BlockKind::EnumeratedList;o+=ordered?"<ol>\n":"<ul>\n";for(const auto&i:b.items)o+="<li>"+render_inlines(i.inlines)+"</li>\n";o+=ordered?"</ol>\n":"</ul>\n";}
  else if(b.kind==BlockKind::DefinitionList){o+="<dl>\n";for(const auto&i:b.items)o+="<dt>"+escape(i.title)+"</dt>\n<dd>"+render_inlines(i.inlines)+"</dd>\n";o+="</dl>\n";}
  else if(b.kind==BlockKind::FieldList){o+="<dl class=\"field-list\">\n";for(const auto&i:b.items)o+="<dt>"+escape(i.title)+"</dt>\n<dd>"+render_inlines(i.inlines)+"</dd>\n";o+="</dl>\n";}
  else if(b.kind==BlockKind::Footnote||b.kind==BlockKind::Citation)o+="<aside class=\""+std::string(b.kind==BlockKind::Footnote?"footnote":"citation")+"\" id=\"footnote-"+escape(b.name,true)+"\"><span>["+escape(b.name)+"]</span> "+render_inlines(b.inlines)+"</aside>\n";
  else if(b.kind==BlockKind::LineBlock){o+="<div class=\"line-block\">\n";std::size_t at=0;while(at<=b.text.size()){auto end=b.text.find('\n',at);o+="<div class=\"line\">"+escape(b.text.substr(at,end-at))+"</div>\n";if(end==std::string::npos)break;at=end+1;}o+="</div>\n";}
  else if(b.kind==BlockKind::Table){o+="<table class=\""+b.style+"\">\n";for(const auto&row:b.items){o+="<tr>";for(const auto&cell:row.items)o+="<td>"+render_inlines(cell.inlines)+"</td>";o+="</tr>\n";}o+="</table>\n";}
  else if(b.kind==BlockKind::Directive){static const std::vector<std::string>admonitions={"attention","caution","danger","error","hint","important","note","tip","warning"};if(std::find(admonitions.begin(),admonitions.end(),b.name)!=admonitions.end())o+="<aside class=\"admonition "+escape(b.name,true)+"\"><p class=\"admonition-title\">"+escape(b.name)+"</p><p>"+render_inlines(b.inlines)+"</p></aside>\n";else if(b.name=="topic"||b.name=="sidebar")o+="<section class=\""+b.name+"\"><h2>"+escape(b.argument)+"</h2><p>"+render_inlines(b.inlines)+"</p></section>\n";else if(b.name=="rubric")o+="<p class=\"rubric\">"+escape(b.argument)+"</p>\n";else if(b.name=="code"||b.name=="code-block")o+="<pre class=\"code "+escape(b.argument,true)+"\">"+escape(b.text)+"</pre>\n";else if(b.name=="parsed-literal")o+="<pre class=\"parsed-literal\">"+render_inlines(b.inlines)+"</pre>\n";else if(b.name=="epigraph"||b.name=="highlights"||b.name=="pull-quote")o+="<blockquote class=\""+b.name+"\"><p>"+render_inlines(b.inlines)+"</p></blockquote>\n";else if(b.name=="compound"||b.name=="container"||b.name=="class")o+="<div class=\""+escape(b.name,true)+"\"><p>"+render_inlines(b.inlines)+"</p></div>\n";else if(b.name=="contents")o+="<nav class=\"contents\"><p class=\"topic-title\">"+escape(b.argument.empty()?"Contents":b.argument)+"</p></nav>\n";else if(b.name=="image"||b.name=="figure")o+="<figure><img src=\""+escape(b.argument,true)+"\" alt=\"\"></figure>\n";}
 }
 return o;
}
void resolve_inlines(std::vector<Inline>&nodes,const Document&doc){for(auto&n:nodes){if(n.kind==InlineKind::Reference){auto found=doc.targets.find(n.target);n.target=found==doc.targets.end()?"#"+n.target:found->second;}else if(n.kind==InlineKind::Substitution){auto found=doc.substitutions.find(n.target);if(found!=doc.substitutions.end()){n.kind=InlineKind::Text;n.text=found->second;}}resolve_inlines(n.children,doc);}}
void resolve_blocks(std::vector<Block>&blocks,const Document&doc){for(auto&b:blocks){resolve_inlines(b.inlines,doc);for(auto&i:b.items)resolve_inlines(i.inlines,doc);resolve_blocks(b.blocks,doc);}}
}
bool expand(const std::string&input,std::string&output,std::string&error,const Options&options){
 output.clear();error.clear();
 std::vector<std::string>stack={options.rst_source_identity};
 if(!expand_resources(input,options,options.rst_source_identity,stack,output,error))return false;
 auto lines=lines_of(normalize(output));
 for(std::size_t i=0;i<lines.size();++i)if(lines[i].rfind(".. raw::",0)==0&&options.rst_diagnostic)options.rst_diagnostic("line "+std::to_string(i+1)+": raw directive disabled");
 return true;
}
bool parse(const std::string&input,Document&doc,std::string&error,const Options&options){doc={};error.clear();if(input.size()>max_input_bytes){error="reStructuredText input exceeds the 64 MiB library limit";return false;}auto normalized=normalize(input);auto lines=lines_of(normalized);static const std::vector<std::string>roles={"code","literal","math","emphasis","em","strong","title-reference","title","subscript","sub","superscript","sup"};static const std::vector<std::string>directives={"attention","caution","danger","error","hint","important","note","tip","warning","topic","sidebar","rubric","epigraph","highlights","pull-quote","compound","container","class","contents","sectnum","header","footer","code","code-block","parsed-literal","include","image","figure","raw","csv-table","list-table"};for(std::size_t index=0;index<lines.size();++index){auto&value=lines[index];if(value.rfind(".. _",0)==0){auto colon=value.find(':',4);if(colon!=std::string::npos){std::string name=slug(value.substr(4,colon-4));std::string target=value.substr(colon+1);if(!target.empty()&&target[0]==' ')target.erase(0,1);doc.targets[name]=target;value.clear();}}else if(value.rfind(".. |",0)==0){auto close=value.find("| replace::",4);if(close!=std::string::npos){std::string name=value.substr(4,close-4);std::string replacement=value.substr(close+11);if(!replacement.empty()&&replacement[0]==' ')replacement.erase(0,1);doc.substitutions[name]=replacement;value.clear();}}if(value.rfind(".. ",0)==0){auto marker=value.find("::",3);if(marker!=std::string::npos){auto name=trim(value.substr(3,marker-3));if(std::find(directives.begin(),directives.end(),name)==directives.end()&&options.rst_diagnostic)options.rst_diagnostic("line "+std::to_string(index+1)+": unknown directive: "+name);}}for(std::size_t at=0;(at=value.find(':',at))!=std::string::npos;++at){auto end=value.find(":`",at+1);if(end==std::string::npos)break;auto role=value.substr(at+1,end-at-1);if(std::find(roles.begin(),roles.end(),role)==roles.end()&&options.rst_diagnostic)options.rst_diagnostic("line "+std::to_string(index+1)+": unknown interpreted role: "+role);at=end+1;}}std::size_t line=0;std::map<char,unsigned>levels;parse_blocks(lines,line,doc.blocks,levels);resolve_blocks(doc.blocks,doc);if(!lines.empty()){doc.source.begin={1,1};doc.source.end={lines.size(),lines.back().size()};}return true;}
std::string render_html(const Document&doc,const Options&){return render_blocks(doc.blocks);}
}
