#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
if ! command -v tsc >/dev/null 2>&1; then
  echo "tsc not installed; generated JSX minifier corpus skipped"
  exit 0
fi
TMP=$(mktemp -d "${TMPDIR:-/tmp}/minify-jsx.XXXXXX")
trap 'rm -rf "$TMP"' EXIT
cat >"$TMP/driver.cpp" <<'CPP'
#include <minify/Minify.h>
#include <iostream>
#include <sstream>
int main(){std::ostringstream s;s<<std::cin.rdbuf();std::string o,e;if(!minify::jsx(s.str(),o,e)){std::cerr<<e;return 2;}std::cout<<o;}
CPP
${CXX:-g++} -std=c++17 -O2 -I"$ROOT/include" -I"$ROOT/src" "$TMP/driver.cpp" "$ROOT/src/Minify.cpp" -o "$TMP/minjsx"

cases=(
'const x=<div>hello  world</div>;'
'const x=<><span>A</span><span>B</span></>;'
'const x=<Foo.Bar value={a > b ? x : y}/>;'
'const x=<my-element data-x="a > b">visible  text</my-element>;'
'const x=<Comp {...props} value={n + 1}/>;'
'const x=<div>{ok ? <span>A</span> : <b>B</b>}</div>;'
'const x=<div>{`hello ${name}`}</div>;'
'const x=<div>{/https?:\/\//.test(url) ? <A/> : null}</div>;'
'const x=<div>{/* keep expression valid */ value}</div>;'
'const x=<Comp child={<span>{value + 1}</span>} />;'
'const x=<div>{items.map(x => <span key={x.id}>{x.name}</span>)}</div>;'
'const x=<div>{(() => { const y={a:1}; return <b>{y.a}</b>; })()}</div>;'
'const x=<div title={"x > y"}>{a >= b ? "A" : "B"}</div>;'
'const x=<div>{/}/.test(s) ? <A/> : <B/>}</div>;'
'const x=<div>{/[/]/.test(s) ? <A/> : null}</div>;'
'const x=<div>{value && <><A/><B/></>}</div>;'
'const x=<Component<number> value={3}/>;'
'const x=<Ns.Component<string> value={"x"}/>;'
'const x=<div><pre>  a   b
 c  </pre></div>;'
'const x=<div>{"{"}{value}{"}"}</div>;'
'const x=<div>{condition ? <Comp value={{a:1,b:{c:2}}}/> : null}</div>;'
'const x=<div>{fn?.(<A/> )}</div>;'
'const x=<div>{new Map([[1, <A/>]]).get(1)}</div>;'
'const x=<div>{asyncFlag ? <A value={awaitable}/> : <B/>}</div>;'
  'const x=<Comp<Array<number>> value={xs}/>;'
  'const x=<Comp<Map<string, number>> value={m}/>;'
  'const x=<Ns.Comp<Array<{x:number}>> value={v}/>;'
  'const x=<div>{flag && (() => <span>{value}</span>)()}</div>;'
  'const x=<div>{flag ?? <span>fallback</span>}</div>;'
  'const x=<div>{obj?.render?.(<A/> )}</div>;'
  'const x=<div>{function(){return <A/>}()}</div>;'
  'const x=<div>{class X { m(){ return <A/>; } }}</div>;'
  'const x=<div data-x={{a:{b:1},c:[1,2]}} />;'
  'const x=<Comp render={() => <><A/><B/></>} />;'
  'const x=<Comp value={condition ? {a:1} : {b:2}} />;'
  'const x=<div>{/a{1,2}/g.test(s) && <A/>}</div>;'
  'const x=<div>{/[{}<>]/.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{String.raw`x${value}`}</div>;'
  'const x=<div aria-label="a &gt; b">x</div>;'
  'const x=<svg><path d="M0 0 L10 10"/></svg>;'
  'const x=<><><A/></><B/></>;'
  'const x=<Comp<T extends U ? A : B> value={v}/>;'
  'const x=<Comp<[number,string]> value={v}/>;'
    'const x=<div>{(a,b)=><span>{a+b}</span>}</div>;'
  'const x=<div>{condition && /[<>]/.test(s) && <A/>}</div>;'
  'const x=<div>{condition ?? (() => <A/>)()}</div>;'
  'const x=<Comp<Promise<Array<number>>> value={p}/>;'
  'const x=<Comp<{a:number;b:string}> value={v}/>;'
  'const x=<Comp<readonly [number,string]> value={v}/>;'
  'const x=<Comp<T extends {a:number} ? A : B> value={v}/>;'
  'const x=<div>{(() => { if(flag) return <A/>; return <B/>; })()}</div>;'
  'const x=<div>{function*(){yield <A/>; return <B/>;}()}</div>;'
  'const x=<div>{async function(){return <A/>;}()}</div>;'
  'const x=<Comp data={{regex:/[<>]/,nested:{x:1}}} />;'
  'const x=<Comp render={(x) => x ? <A/> : <B/>} />;'
  'const x=<div>{array?.map?.(x => <A key={x}/>) ?? null}</div>;'
  'const x=<div>{new class {render(){return <A/>}}().render()}</div>;'
  'const x=<div>{class {static render(){return <A/>}}.render()}</div>;'
  'const x=<div>{({render(){return <A/>}}).render()}</div>;'
  'const x=<div>{/\/\*x\*\//.test(s) ? <A/> : null}</div>;'
  'const x=<div>{/\/\/x/.test(s) ? <A/> : null}</div>;'
  'const x=<div>{/^(?<x>a)(?=\k<x>)/.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{String.raw`<tag>${value}</tag>`}</div>;'
  'const x=<div dangerouslySetInnerHTML={{__html:"<b>x</b>"}} />;'
  'const x=<svg><g><path d={`M ${x} ${y}`}/></g></svg>;'
  'const x=<><Comp<number> value={1}/><Comp<string> value={"x"}/></>;'
  'const x=<div>{true ? <Comp<Map<string,Array<number>>> value={m}/> : null}</div>;'
  'const x=<div>{awaitable && <Comp<Promise<string>> value={awaitable}/>}</div>;'
  'const x=<Comp<{a:{b:Array<number>}}> value={v}/>;'
  'const x=<Comp<(x:number)=>string> value={fn}/>;'
  'const x=<Comp<keyof typeof obj> value={k}/>;'
  'const x=<div>{/[\]\[]/.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{/(?<word>\w+)\s+\k<word>/.test(s) && <A/>}</div>;'
  'const x=<div>{/\x2f\x2a/.test(s) ? <A/> : null}</div>;'
  'const x=<div>{String.raw`/${value}/ <>`}</div>;'
  'const x=<div>{(() => { try { return <A/> } finally {} })()}</div>;'
  'const x=<div>{(() => { switch(v){case 1:return <A/>;default:return <B/>} })()}</div>;'
  'const x=<div>{(() => { for(const v of xs){ if(v)return <A/> } return <B/> })()}</div>;'
  'const x=<Comp onClick={() => { const r=/[<>]/; return r.test(s); }} />;'
  'const x=<Comp render={async () => <A/>} />;'
  'const x=<Comp render={function*(){yield <A/>;}} />;'
  'const x=<Comp render={async function*(){yield <A/>;}} />;'
  'const x=<div>{class C { static { this.x=1 } static render(){return <A/>} }.render()}</div>;'
  'const x=<div>{({get x(){return <A/>}}).x}</div>;'
  'const x=<div>{({*g(){yield <A/>}}).g().next().value}</div>;'
  'const x=<div>{({async f(){return <A/>}}).f()}</div>;'
  'const x=<svg><foreignObject><div>{value}</div></foreignObject></svg>;'
  'const x=<math><mrow><mi>x</mi><mo>+</mo><mi>y</mi></mrow></math>;'
  'const x=<div data-json={JSON.stringify({x:"<>",r:"/*"})} />;'
  'const x=<div>{condition ? <><A key="a"/><B key="b"/></> : <C/>}</div>;'
  'const x=<Comp<Awaited<Promise<number>>> value={v}/>;'
  'const x=<Comp<{readonly a?:number}> value={v}/>;'
  'const x=<Comp<{[K in keyof T]:T[K]}> value={v}/>;'
  'const x=<Comp<T extends infer U ? U : never> value={v}/>;'
  'const x=<div>{/^a.b$/s.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{/a/d.test(s) && <A/>}</div>;'
  'const x=<div>{/(?<!a)b/.test(s) ? <A/> : null}</div>;'
  'const x=<div>{/[^/*<>]+/.test(s) ? <A/> : <B/>}</div>;'
  'const x=<Comp title={`value: ${x > y ? "a" : "b"}`} />;'
  'const x=<Comp data={{html:"</script><div>",css:"a>b{c:d}"}} />;'
  'const x=<div>{(() => { class C{m(){return <A/>}} return new C().m(); })()}</div>;'
  'const x=<div>{(() => { function f(){return <A/>} return f(); })()}</div>;'
  'const x=<div>{(() => { async function f(){return <A/>} return f(); })()}</div>;'
  'const x=<div>{(() => { function* f(){yield <A/>} return f().next().value; })()}</div>;'
  'const x=<div>{condition ? <Comp<{a:number}> value={{a:1}}/> : <Comp<string> value="x"/>}</div>;'
  'const x=<svg><text>{value > 1 ? "a  b" : "c"}</text></svg>;'
  'const x=<math><mfrac><mi>{a}</mi><mi>{b}</mi></mfrac></math>;'
  'const x=<><Comp render={() => <A/>}/>{condition && <B/>}</>;'
  'const x=<div>{obj?.[key] ?? <Fallback/>}</div>;'
  'const x=<div>{(() => ({render:() => <A/>})).call(null).render()}</div>;'
  'const x=<Comp<Record<string,Array<number>>> value={v}/>;'
  'const x=<Comp<Partial<{a:number;b:string}>> value={v}/>;'
  'const x=<Comp<Pick<T,"a"|"b">> value={v}/>;'
  'const x=<Comp<T["a"]> value={v}/>;'
  'const x=<Comp<T[keyof T]> value={v}/>;'
  'const x=<Comp<`${string}-${number}`> value={v}/>;'
  'const x=<div>{class C<T>{m(x:T){return <A value={x}/>}}}</div>;'
  'const x=<div>{function f<T>(x:T){return <A value={x}/>}}</div>;'
  'const x=<div>{(<T,>(x:T)=><A value={x}/>)(1)}</div>;'
  'const x=<div>{((x:number):JSX.Element=><A value={x}/>)(1)}</div>;'
  'const x=<div>{condition ? <A>{/[/<>]/.test(s) ? "x" : "y"}</A> : null}</div>;'
  'const x=<div>{/https?:\/\/(?:www\.)?example\.com/.test(url) && <A/>}</div>;'
  'const x=<div>{/(?<=foo)bar/.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{/(?<!foo)bar/.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{/\\p{Emoji_Presentation}/u.test(s) ? <A/> : null}</div>;'
  'const x=<div>{({[key]:<A/>})[key]}</div>;'
  'const x=<div>{new Map([[key,<A/>],[other,<B/>]]).get(key)}</div>;'
  'const x=<Comp {...{a:1,b:{c:<A/>}}} />;'
  'const x=<Comp children={[<A key="a"/>,<B key="b"/>]} />;'
  'const x=<div>{[1,2].map((n:number)=><A key={n} value={n}/>)}</div>;'
  'const x=<div>{Promise.resolve(<A/>).then(x=>x)}</div>;'
  'const x=<div>{(() => { const r = /[<>]/; return r.test(s) ? <A/> : <B/>; })()}</div>;'
  'const x=<div>{(() => { const t = `<> ${value}`; return <A value={t}/>; })()}</div>;'
  'const x=<div>{(() => { const o = {x:<A/>}; return o.x; })()}</div>;'
  'const x=<svg><defs><linearGradient id="g"><stop offset="0%"/></linearGradient></defs><rect fill="url(#g)"/></svg>;'
  'const x=<svg><foreignObject><section><A/></section></foreignObject></svg>;'
  'const x=<math><msup><mi>x</mi><mn>{n}</mn></msup></math>;'
  'const x=<><template data-x={value}><A/></template><B/></>;'
  'const x=<Comp<T extends (...args:any[])=>any ? ReturnType<T> : never> value={v}/>;'
  'const x=<Comp<{new(x:number):{x:number}}> value={Ctor}/>;'

  'const x=<div>{({a:1} satisfies Record<string,unknown>).a}</div>;'
  'const x=<div>{((x:number):x is number=>true)(1) ? <A/> : <B/>}</div>;'
  'const x=<Comp<Array<{x:number;y?:string}>> value={v}/>;'
  'const x=<Comp<ReadonlyMap<string,ReadonlyArray<number>>> value={m}/>;'
  'const x=<Comp<T extends infer U ? U : never> value={v}/>;'
  'const x=<div>{(<T extends Record<string,unknown>>(x:T)=><A value={x}/> )({})}</div>;'
  'const x=<div>{(<T=number,>(x:T)=><A value={x}/>)(1)}</div>;'
  'const x=<div>{(<const T,>(x:T)=><A value={x}/>)([1] as const)}</div>;'
  'const x=<div>{foo satisfies {render():unknown} ? <A/> : null}</div>;'
  'const x=<div>{(foo as {x:number}).x ?? <A/>}</div>;'
  'const x=<div>{/\\p{Script=Greek}+/u.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{/(?<!ab)c/.test(s) && <A/>}</div>;'
  'const x=<div>{/(?<x>a|b)c\\k<x>/.test(s) && <A/>}</div>;'
  'const x=<Comp value={{a:{b:{c:[1,2,3]}}}} render={({a}) => <A value={a.b.c}/>} />;'
  'const x=<><svg><foreignObject><section>{x}</section></foreignObject></svg><A/></>;'
  'const x=<div>{(() => { class C<T>{render(v:T){return <A value={v}/>}} return new C<number>().render(1) })()}</div>;'
  'const x=<div>{(() => { const f=<T,>(x:T)=>x; return <A value={f(1)}/> })()}</div>;'
  'const x=<div>{(() => { const f=<T extends {}>(x:T)=>x; return <A value={f({})}/> })()}</div>;'
  'const x=<Comp render={<T,>(x:T)=><A value={x}/>} />;'
  'const x=<Comp render={<T extends {}>(x:T)=><A value={x}/>} />;'
  'const x=<Comp<NoInfer<T>> value={v}/>;'
  'const x=<Comp<Awaited<Promise<number>>> value={v}/>;'
  'const x=<Comp<Partial<Record<string,number>>> value={v}/>;'
  'const x=<Comp<{readonly [K in keyof T]?:T[K]}> value={v}/>;'
  'const x=<Comp<T extends `${string}-${number}` ? A : B> value={v}/>;'
  'const x=<div>{(<T extends keyof U,U extends object>(x:T,y:U)=><A value={y[x]}/>)(k,o)}</div>;'
  'const x=<div>{(<T=string,U=T,>(x:U)=><A value={x}/>)('"'"'x'"'"')}</div>;'
  'const x=<Comp render={<T extends readonly unknown[],>(...x:T)=><A value={x.length}/>} />;'
  'const x=<div>{(() => { const {a:{b=1}={}}=obj; return <A value={b}/> })()}</div>;'
  'const x=<div>{(() => { try{return <A/>}catch({message}){return <B value={message}/>}})()}</div>;'
  'const x=<div>{(() => { for(const {a} of xs){if(a)return <A value={a}/>}return null})()}</div>;'
  'const x=<div>{/(?<!ab)c/.test(s) ? <A/> : <B/>}</div>;'
  'const x=<div>{/(?<x>a|b)c\\k<x>/.test(s) && <A/>}</div>;'
  'const x=<div>{/(?<=\\bfoo\\s)bar/.test(s) && <A/>}</div>;'
  'const x=<Comp value={foo?.bar?.baz ?? (() => <A/>)()} />;'
  'const x=<Comp render={() => ({a:1} satisfies {a:number}) ? <A/> : <B/>} />;'
  'const x=<Comp render={() => (<A/> as unknown as JSX.Element)} />;'
  'const x=<svg><style>{`.a{fill:${color}}`}</style><path className="a"/></svg>;'
  'const x=<math><mfrac><mi>{a}</mi><mi>{b}</mi></mfrac></math>;'
  'const x=<><Comp<number> value={1}/>{flag && <Comp<string> value="x"/>}</>;'
)

mkdir -p "$TMP/orig" "$TMP/min" "$TMP/min2"
count=0
for source in "${cases[@]}"; do
  file=$(printf '%03d.tsx' "$count")
  printf '%s\n' "$source" >"$TMP/orig/$file"
  "$TMP/minjsx" <"$TMP/orig/$file" >"$TMP/min/$file"
  "$TMP/minjsx" <"$TMP/min/$file" >"$TMP/min2/$file"
  cmp "$TMP/min/$file" "$TMP/min2/$file"
  count=$((count+1))
done

# Validate the full original and minified corpora with only two TypeScript
# startups; this keeps the test scalable as the corpus grows.
tsc --noCheck --pretty false --target es2022 --jsx preserve --moduleDetection force --noEmit "$TMP/orig"/*.tsx
tsc --noCheck --pretty false --target es2022 --jsx preserve --moduleDetection force --noEmit "$TMP/min"/*.tsx

echo "Generated JSX minifier syntax/idempotence corpus passed ($count programs)"
