from pathlib import Path
import subprocess,shlex,json
p=Path(__file__).parent.resolve();p=p/'file-phases';p.mkdir(exist_ok=True)
names=['FileConstruction','Registry','FileTag','CheckedPath','PathResolution','Cwd','Open','Write','Save','Comparison','ParentCheck','Permissions','TempName','Stream','AtomicReplace','SavedState','Close','FileTeardown']
h=Path('.build/cp410/phases/Phases.h').read_text();a=h.index('enum Id {');b=h.index('struct Entry',a);h=h[:a]+'enum Id {'+','.join(names)+',Count};\ninline const char* names[]={'+','.join(json.dumps(x) for x in names)+'};\n'+h[b:];(p/'Phases.h').write_text(h);(p/'Alloc.cpp').write_text(Path('.build/cp410/phases/Alloc.cpp').read_text())
s=Path('src/ParserExpression.cpp').read_text();s='#include "Phases.h"\n'+s
s=s.replace('auto resolve_path=[&](const std::string& raw)->fs::path{','auto resolve_path=[&](const std::string& raw)->fs::path{cp51::Phase path_phase(cp51::PathResolution);',1)
a=s.index('auto resolve_path=');b=s.index('std::vector<nift::detail::SourceText> args;',a);chunk=s[a:b].replace('fs::current_path()', 'cp51::run<cp51::Cwd>([&]{return fs::current_path();})').replace('size_t i,fs::path& p)->bool{','size_t i,fs::path& p)->bool{cp51::Phase checked_phase(cp51::CheckedPath);');s=s[:a]+chunk+s[b:]
a=s.index('auto fit=file_instances_.find(');b=s.index('if(method=="to_lower"',a);chunk=s[a:b]
for name,marker in [('Open','if(method=="open"){'),('Close','if(method=="close"){'),('Write','if(method=="write"||method=="write_line"){'),('Save','if(method=="save"){')]:
 assert chunk.count(marker)==1,(name,chunk.count(marker));chunk=chunk.replace(marker,marker+'cp51::Phase method_phase(cp51::'+name+');')
chunk=chunk.replace('auto dirty=[&](){','auto dirty=[&](){cp51::Phase comparison_phase(cp51::Comparison);')
chunk=chunk.replace('auto parent=f->path.parent_path();','cp51::Phase parent_phase(cp51::ParentCheck);auto parent=f->path.parent_path();').replace('fs::perms perms=fs::perms::unknown;','parent_phase.finish();cp51::Phase perms_phase(cp51::Permissions);fs::perms perms=fs::perms::unknown;').replace('fs::path tmp=f->path;','perms_phase.finish();cp51::Phase temp_phase(cp51::TempName);fs::path tmp=f->path;').replace('{std::ofstream o(tmp,','temp_phase.finish();{cp51::Phase stream_phase(cp51::Stream);std::ofstream o(tmp,').replace('filesystem::replace_file_atomic(tmp,f->path)','cp51::run<cp51::AtomicReplace>([&]{return filesystem::replace_file_atomic(tmp,f->path);})').replace('f->saved=f->working;','{cp51::Phase saved_phase(cp51::SavedState);f->saved=f->working;}')
s=s[:a]+chunk+s[b:];(p/'ParserExpression.cpp').write_text(s)
s=Path('src/Parser.cpp').read_text();s='#include "Phases.h"\n'+s;s=s.replace('bool Parser::make_file_value(fs::path path, nift::RuntimeValue& out, std::string& error) {','bool Parser::make_file_value(fs::path path, nift::RuntimeValue& out, std::string& error) {cp51::Phase construction_phase(cp51::FileConstruction);').replace('file_instances_[std::to_string(id)] = std::move(file);','{cp51::Phase registry_phase(cp51::Registry);file_instances_[std::to_string(id)] = std::move(file);}').replace('out = nift::RuntimeValue(std::string("\\x1fnift:file:") + std::to_string(id));','{cp51::Phase tag_phase(cp51::FileTag);out = nift::RuntimeValue(std::string("\\x1fnift:file:") + std::to_string(id));}').replace('    finalize_execution_workers();\n}', '    finalize_execution_workers();\n    {cp51::Phase teardown_phase(cp51::FileTeardown);file_instances_.clear();}\n}',1);(p/'Parser.cpp').write_text(s)
flags=['g++','-I'+str(p),'-Isrc','-Iinclude','-Iminifypp/include','-Iminifypp/src','-Imarkuppp/include','-Imarkuppp/vendor/cmark','-I.build/libffi/x86_64-linux-gnu-cc/install/include','-std=c++17','-O2','-Wall','-Wextra','-pedantic','-pthread'];cmds=[]
for name in ['Alloc','Parser','ParserExpression']:cmds.append(flags+['-c',str(p/(name+'.cpp')),'-o',str(p/(name+'.o'))])
lines=Path('.build/cp410-wave3/build-string.log').read_text().splitlines();link=shlex.split(next(x for x in reversed(lines) if x.startswith('g++ ') and x.endswith('-o nift')));link=[str(p/(Path(x).stem+'.o')) if x in ['src/Parser.o','src/ParserExpression.o'] else x for x in link];link.insert(1,str(p/'Alloc.o'));link[-1]=str(p/'nift');cmds.append(link);(p/'build.json').write_text(json.dumps(cmds,indent=2)+'\n')
for c in cmds:subprocess.run(c,check=True)
