<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Nift\Nift.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)/../../../libnift_c.so" Link="libnift_c.so" CopyToOutputDirectory="PreserveNewest" Condition="Exists('$(MSBuildProjectDirectory)/../../libnift_c.so')" />
  </ItemGroup>
</Project>
