#pragma once
#include "Json.h"
#include "FrontMatter.h"
#include "FileSystem.h"
#include <filesystem>
#include <cmath>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace content_model {
struct Field { std::string name; std::string type; bool array=false; bool required=true; bool has_default=false; json::Document default_value; std::string taxonomy; };
struct Schema { std::string name; std::vector<Field> fields; std::string source; };
struct Taxonomy { std::string name; bool hierarchical=false; std::string source; };
struct Model { std::map<std::string,Schema> schemas; std::map<std::string,Taxonomy> taxonomies; std::vector<std::string> errors; };
inline std::string trim(std::string s){auto a=s.find_first_not_of(" \t\r\n");if(a==std::string::npos)return{};auto b=s.find_last_not_of(" \t\r\n");return s.substr(a,b-a+1);}
inline bool ident(const std::string&s){if(s.empty()||!(std::isalpha((unsigned char)s[0])||s[0]=='_'))return false;for(char c:s)if(!(std::isalnum((unsigned char)c)||c=='_'||c=='-'))return false;return true;}
inline bool parse_decl_blocks(const std::string& text,const std::string& kind,std::vector<std::pair<std::string,std::string>>& out,std::string& err){
 std::string needle="@"+kind+"("; size_t p=0; while((p=text.find(needle,p))!=std::string::npos){size_t ns=p+needle.size(), nc=text.find(')',ns);if(nc==std::string::npos){err=kind+" declaration missing ')'";return false;}std::string name=trim(text.substr(ns,nc-ns));if(!ident(name)){err="invalid "+kind+" name: "+name;return false;}size_t q=nc+1;while(q<text.size()&&std::isspace((unsigned char)text[q]))++q;std::string body;if(q<text.size()&&text[q]=='{'){int d=1;size_t b=++q;for(;q<text.size()&&d;q++){if(text[q]=='{')d++;else if(text[q]=='}')d--;}if(d){err=kind+" declaration missing '}'";return false;}body=text.substr(b,q-b-1);}out.push_back({name,body});p=q;}return true;
}
inline bool parse_schema_body(const std::string& body,Schema& s,std::string& err){std::istringstream in(body);std::string line;while(std::getline(in,line)){line=trim(line);if(line.empty()||line[0]=='#'||line.rfind("//",0)==0)continue;if(line.back()==';')line.pop_back();auto c=line.find(':');if(c==std::string::npos){err="schema "+s.name+": expected field: type";return false;}Field f;f.name=trim(line.substr(0,c));std::string rhs=trim(line.substr(c+1));if(!ident(f.name)){err="schema "+s.name+": invalid field name";return false;}auto eq=rhs.find('=');std::string def;if(eq!=std::string::npos){def=trim(rhs.substr(eq+1));rhs=trim(rhs.substr(0,eq));f.has_default=true;f.required=false;f.default_value=frontmatter::scalar(def);}if(!rhs.empty()&&rhs.back()=='?'){f.required=false;rhs.pop_back();rhs=trim(rhs);}if(rhs.size()>=2&&rhs.substr(rhs.size()-2)=="[]"){f.array=true;rhs=trim(rhs.substr(0,rhs.size()-2));}if(rhs.rfind("taxonomy(",0)==0&&rhs.back()==')'){f.type="taxonomy";f.taxonomy=trim(rhs.substr(9,rhs.size()-10));if(!ident(f.taxonomy)){err="schema "+s.name+": invalid taxonomy reference";return false;}}else f.type=rhs;if(f.type.empty()){err="schema "+s.name+": empty type";return false;}for(auto& x:s.fields)if(x.name==f.name){err="schema "+s.name+": duplicate field "+f.name;return false;}s.fields.push_back(std::move(f));}return true;}
inline bool type_ok(const json::Document& v,const std::string&t){if(t=="any")return true;if(t=="string"||t=="date")return v.is_string();if(t=="bool"||t=="boolean")return v.is_bool();if(t=="number")return v.is_number();if(t=="int"||t=="integer")return v.is_number()&&std::isfinite(v.num)&&std::floor(v.num)==v.num;if(t=="object")return v.is_object();if(t=="array")return v.is_array();if(t=="null")return v.is_null();if(t=="taxonomy")return v.is_string();return true;}
inline bool validate(json::Document& metadata,const Schema&s,const Model&m,std::string&err){if(!metadata.is_object()){err="schema "+s.name+": metadata must be an object";return false;}for(const auto&f:s.fields){if(!metadata.has(f.name)){if(f.has_default){metadata[f.name]=f.default_value;continue;}if(f.required){err="schema "+s.name+": missing required field '"+f.name+"'";return false;}continue;}const auto&v=metadata[f.name];if(f.array){if(!v.is_array()){err="schema "+s.name+" field '"+f.name+"': expected array";return false;}for(const auto&x:v.array)if(!type_ok(x,f.type)){err="schema "+s.name+" field '"+f.name+"': invalid array item for "+f.type;return false;}}else if(!type_ok(v,f.type)){err="schema "+s.name+" field '"+f.name+"': expected "+f.type;return false;}if(f.type=="taxonomy"&&!m.taxonomies.count(f.taxonomy)){err="schema "+s.name+" field '"+f.name+"': unknown taxonomy '"+f.taxonomy+"'";return false;}}return true;}
inline bool confined(const std::filesystem::path&root,const std::string&rel,std::filesystem::path&out){out=(root/rel).lexically_normal();return filesystem::path_within(root,out);}
inline Model load(const std::filesystem::path&root,const std::vector<std::string>&schema_files,const std::vector<std::string>&tax_files){Model m;for(const auto&rel:tax_files){std::filesystem::path p;if(!confined(root,rel,p)){m.errors.push_back("taxonomy path escapes project root: "+rel);continue;}if(p.extension()!=".tax"){m.errors.push_back("taxonomy source must use .tax: "+rel);continue;}if(!filesystem::file_exists(p)){m.errors.push_back("taxonomy source does not exist: "+rel);continue;}std::vector<std::pair<std::string,std::string>> ds;std::string e;if(!parse_decl_blocks(filesystem::read_file(p),"taxonomy",ds,e)){m.errors.push_back(rel+": "+e);continue;}for(auto&d:ds){if(m.taxonomies.count(d.first)){m.errors.push_back("duplicate taxonomy: "+d.first);continue;}Taxonomy t;t.name=d.first;t.source=rel;auto b=d.second;if(b.find("hierarchical")!=std::string::npos&&b.find("true")!=std::string::npos)t.hierarchical=true;m.taxonomies[t.name]=t;}}
 for(const auto&rel:schema_files){std::filesystem::path p;if(!confined(root,rel,p)){m.errors.push_back("schema path escapes project root: "+rel);continue;}if(p.extension()!=".schema"){m.errors.push_back("schema source must use .schema: "+rel);continue;}if(!filesystem::file_exists(p)){m.errors.push_back("schema source does not exist: "+rel);continue;}std::vector<std::pair<std::string,std::string>> ds;std::string e;if(!parse_decl_blocks(filesystem::read_file(p),"schema",ds,e)){m.errors.push_back(rel+": "+e);continue;}for(auto&d:ds){if(m.schemas.count(d.first)){m.errors.push_back("duplicate schema: "+d.first);continue;}Schema s;s.name=d.first;s.source=rel;if(!parse_schema_body(d.second,s,e)){m.errors.push_back(rel+": "+e);continue;}m.schemas[s.name]=std::move(s);}}
 return m;}
}
