#pragma once
#include "Json.h"
#include "Types.h"
#include "FileSystem.h"
#include <filesystem>
#include <sstream>
#include <cctype>
namespace frontmatter {
struct Parsed { bool present=false; json::Document value=json::Document::make_object(); std::string body; std::string error; };
inline std::string trim(std::string s){auto a=s.find_first_not_of(" \t\r");if(a==std::string::npos)return{};auto b=s.find_last_not_of(" \t\r");return s.substr(a,b-a+1);}
inline json::Document scalar(const std::string& raw){std::string s=trim(raw);if(s=="true")return json::Document(true);if(s=="false")return json::Document(false);if(s=="null"||s=="~")return json::Document();if(s.size()>=2&&((s.front()=='"'&&s.back()=='"')||(s.front()=='\''&&s.back()=='\'')))return json::Document(s.substr(1,s.size()-2));char* e=nullptr;double n=strtod(s.c_str(),&e);if(e&&*e=='\0'&&!s.empty())return json::Document(n);return json::Document(s);}
inline bool parse_yaml_object(const std::string& text,json::Document& out,std::string& error){out=json::Document::make_object();std::istringstream in(text);std::string line,last;size_t ln=0;while(std::getline(in,line)){++ln;if(!line.empty()&&line.back()=='\r')line.pop_back();if(trim(line).empty()||trim(line).rfind("#",0)==0)continue;size_t indent=line.find_first_not_of(" \t");if(indent==std::string::npos)continue;std::string t=line.substr(indent);if(t.rfind("- ",0)==0){if(last.empty()||!out[last].is_array()){error="front matter list item without an array key at line "+std::to_string(ln);return false;}out[last].push_back(scalar(t.substr(2)));continue;}auto c=t.find(':');if(c==std::string::npos){error="front matter expected key: value at line "+std::to_string(ln);return false;}std::string key=trim(t.substr(0,c)),val=trim(t.substr(c+1));if(key.empty()){error="front matter has an empty key at line "+std::to_string(ln);return false;}if(out.has(key)){error="front matter duplicate key '"+key+"'";return false;}last=key;if(val.empty())out[key]=json::Document::make_array();else out[key]=scalar(val);}return true;}
inline Parsed parse_inline(const std::string& source){Parsed r;r.body=source;if(source.rfind("---\n",0)!=0&&source.rfind("---\r\n",0)!=0)return r;size_t first=source.find('\n');size_t pos=first+1,end=std::string::npos,next=pos;while(next<source.size()){size_t nl=source.find('\n',next);std::string line=source.substr(next,(nl==std::string::npos?source.size():nl)-next);if(!line.empty()&&line.back()=='\r')line.pop_back();if(line=="---"){end=next;pos=(nl==std::string::npos?source.size():nl+1);break;}if(nl==std::string::npos)break;next=nl+1;}if(end==std::string::npos){r.error="unterminated front matter";return r;}r.present=true;std::string yaml=source.substr(first+1,end-(first+1));if(!parse_yaml_object(yaml,r.value,r.error))return r;r.body=source.substr(pos);return r;}
inline bool load_external(const std::filesystem::path& root,const std::string& rel,json::Document& out,std::string& error){std::filesystem::path p=(root/rel).lexically_normal();auto rr=root.lexically_normal().generic_string(),pp=p.generic_string();if(pp!=rr&&pp.rfind(rr+"/",0)!=0){error="frontmatter path escapes project root";return false;}if(!filesystem::file_exists(p)){error="frontmatter file does not exist: "+rel;return false;}std::string s=filesystem::read_file(p);if(p.extension()==".json"){std::string e;if(!json::Document::parse(s,out,e)||!out.is_object()){error="invalid JSON frontmatter"+(e.empty()?std::string{}:": "+e);return false;}return true;}return parse_yaml_object(s,out,error);}
}
